## Data Preprocessing

1. Check for missing values: Check if there are any missing values in the dataset and decide on how to handle them. If there are a lot of missing values, you may consider dropping those rows or imputing them with appropriate values.

2. Check for duplicates: Check if there are any duplicate rows in the dataset and remove them if necessary.

3. Data type conversion: Check if the data types of the columns are appropriate. For example, the 'UID' column should be of integer data type, while the 'productID' column should be categorical.

4. Check for outliers: Check if there are any outliers in the dataset, especially in the continuous variables such as 'air temperature', 'process temperature', 'rotational speed', 'torque', and 'tool wear'. You may consider removing or adjusting the outliers depending on the context.

5. Feature engineering: Create new features that may be relevant for predictive maintenance. For example, you may create a new feature that combines the 'air temperature' and 'process temperature' to represent the temperature difference, which may be an important indicator of machine failure.

6. Label encoding: Convert the categorical variable 'productID' to numerical values using label encoding or one-hot encoding, depending on the algorithm you plan to use.

7. Feature scaling: Normalize or standardize the continuous variables to ensure that they have similar ranges. This will help the machine learning algorithm to converge faster.

8. Balance the dataset: Check if the dataset is balanced in terms of the 'machine failure' label. If there are a lot more non-failure instances than failure instances, you may consider oversampling or undersampling to balance the dataset.

9. Save the preprocessed dataset: Save the preprocessed dataset in a suitable format, such as CSV or Parquet, for future use.

## Import Libraries

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Read the data

In [11]:
df = pd.read_csv("D:/Kongsberg/Data/data.csv")

In [12]:
df

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,M24855,M,298.8,308.4,1604,29.5,14,0,0,0,0,0,0
9996,9997,H39410,H,298.9,308.4,1632,31.8,17,0,0,0,0,0,0
9997,9998,M24857,M,299.0,308.6,1645,33.4,22,0,0,0,0,0,0
9998,9999,H39412,H,299.0,308.7,1408,48.5,25,0,0,0,0,0,0
9999,10000,M24859,M,299.0,308.7,1500,40.2,30,0,0,0,0,0,0

## Missing values

In [13]:
df.isna().sum()

UDI                        0
Product ID                 0
Type                       0
Air temperature [K]        0
Process temperature [K]    0
Rotational speed [rpm]     0
Torque [Nm]                0
Tool wear [min]            0
Machine failure            0
TWF                        0
HDF                        0
PWF                        0
OSF                        0
RNF                        0
dtype: int64

## Check for duplicates

In [14]:
df.duplicated().sum()

np.int64(0)

## Data type conversion

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   UDI                      10000 non-null  int64
 1   Product ID               10000 non-null  object
 2   Type                     10000 non-null  object
 3   Air temperature [K]      10000 non-null  float64
 4   Process temperature [K]  10000 non-null  float64
 5   Rotational speed [rpm]   10000 non-null  int64
 6   Torque [Nm]              10000 non-null  float64
 7   Tool wear [min]          10000 non-null  int64
 8   Machine failure          10000 non-null  int64
 9   TWF                      10000 non-null  int64
 10  HDF                      10000 non-null  int64
 11  PWF                      10000 non-null  int64
 12  OSF                      10000 non-null  int64
 13  RNF                      10000 non-null  int64
dtypes: float64(3), int64(9), object(2)
memory usage: 1.1+ MB

## Feature engineering

### creating 'type of failure' feature

In [16]:
def type_of_failure(row_name):
    if df.loc[row_name, 'TWF'] == 1:
        df.loc[row_name, 'type_of_failure'] = 'TWF'
    elif df.loc[row_name, 'HDF'] == 1:
        df.loc[row_name, 'type_of_failure'] = 'HDF'
    elif df.loc[row_name, 'PWF'] == 1:
        df.loc[row_name, 'type_of_failure'] = 'PWF'
    elif df.loc[row_name, 'OSF'] == 1:
        df.loc[row_name, 'type_of_failure'] = 'OSF'
    elif df.loc[row_name, 'RNF'] == 1:
        df.loc[row_name, 'type_of_failure'] = 'RNF'

df.apply(lambda row: type_of_failure(row.name), axis=1)
df['type_of_failure'].replace(np.nan, 'no failure', inplace=True)
df.drop(['TWF', 'HDF', 'PWF', 'OSF', 'RNF'], axis=1, inplace=True)
df.head()

C:\Users\gadha\AppData\Local\Temp\ipykernel_7376\2704846465.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['type_of_failure'].replace(np.nan, 'no failure', inplace=True)

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,type_of_failure
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,no failure
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,no failure
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,no failure
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,no failure
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,no failure

In [17]:
df.drop(['UDI', 'Product ID'], axis=1, inplace=True)
df.head()

,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,type_of_failure
0,M,298.1,308.6,1551,42.8,0,0,no failure
1,L,298.2,308.7,1408,46.3,3,0,no failure
2,L,298.1,308.5,1498,49.4,5,0,no failure
3,L,298.2,308.6,1433,39.5,7,0,no failure
4,L,298.2,308.7,1408,40.0,9,0,no failure

converting Kelvin to Celsius

In [18]:
df['Air temperature [c]'] = df['Air temperature [K]'] - 273.15
df['Process temperature [c]'] = df['Process temperature [K]'] - 273.15
df.drop(['Air temperature [K]', 'Process temperature [K]'], axis=1, inplace=True)
df.head()

,Type,Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,type_of_failure,Air temperature [c],Process temperature [c]
0,M,1551,42.8,0,0,no failure,24.95,35.45
1,L,1408,46.3,3,0,no failure,25.05,35.55
2,L,1498,49.4,5,0,no failure,24.95,35.35
3,L,1433,39.5,7,0,no failure,25.05,35.45
4,L,1408,40.0,9,0,no failure,25.05,35.55

## Categorical Encoding

In [19]:
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder(categories=[['L', 'M', 'H']])

df['Type'] = encoder.fit_transform(df[['Type']])
df.head()

,Type,Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,type_of_failure,Air temperature [c],Process temperature [c]
0,1.0,1551,42.8,0,0,no failure,24.95,35.45
1,0.0,1408,46.3,3,0,no failure,25.05,35.55
2,0.0,1498,49.4,5,0,no failure,24.95,35.35
3,0.0,1433,39.5,7,0,no failure,25.05,35.45
4,0.0,1408,40.0,9,0,no failure,25.05,35.55

In [20]:
df['Type'].value_counts()

Type
0.0    6000
1.0    2997
2.0    1003
Name: count, dtype: int64

### Label Encoding

In [21]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

df['type_of_failure'] = encoder.fit_transform(df['type_of_failure'])
df.head()

,Type,Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,type_of_failure,Air temperature [c],Process temperature [c]
0,1.0,1551,42.8,0,0,5,24.95,35.45
1,0.0,1408,46.3,3,0,5,25.05,35.55
2,0.0,1498,49.4,5,0,5,24.95,35.35
3,0.0,1433,39.5,7,0,5,25.05,35.45
4,0.0,1408,40.0,9,0,5,25.05,35.55

In [22]:
df.loc[df['Machine failure'] == 1]

,Type,Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,type_of_failure,Air temperature [c],Process temperature [c]
50,0.0,2861,4.6,143,1,2,25.75,35.95
69,0.0,1410,65.7,191,1,2,25.75,35.85
77,0.0,1455,41.3,208,1,4,25.65,35.75
160,0.0,1282,60.7,216,1,1,25.25,35.05
161,0.0,1412,52.3,218,1,1,25.15,34.95
...,...,...,...,...,...,...,...,...
9758,0.0,2271,16.2,218,1,4,25.45,36.65
9764,0.0,1294,66.7,12,1,2,25.35,36.35
9822,0.0,1360,60.9,187,1,1,25.35,36.25
9830,0.0,1337,56.1,206,1,1,25.15,36.15
9974,0.0,1361,68.2,172,1,2,25.45,35.05

In [23]:
encoder.classes_

array(['HDF', 'OSF', 'PWF', 'RNF', 'TWF', 'no failure'], dtype=object)

In [24]:
classes = [0, 1, 2, 3, 4, 5]
encoder.inverse_transform(classes)

array(['HDF', 'OSF', 'PWF', 'RNF', 'TWF', 'no failure'], dtype=object)

In [25]:
df['type_of_failure'].value_counts()

type_of_failure
5    9652
0     115
2      91
1      78
4      46
3      18
Name: count, dtype: int64

In [26]:
df.iloc[6000]

Type                          2.00
Rotational speed [rpm]     1431.00
Torque [Nm]                  43.20
Tool wear [min]               0.00
Machine failure               0.00
type_of_failure               5.00
Air temperature [c]          27.25
Process temperature [c]      37.05
Name: 6000, dtype: float64

### Feature Scaling

In [27]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scale_cols = ['Rotational speed [rpm]', 'Torque [Nm]', 'Tool wear [min]', 'Air temperature [c]', 'Process temperature [c]']

df_scaled = scaler.fit_transform(df[scale_cols])
df_scaled = pd.DataFrame(df_scaled)
df_scaled.columns = scale_cols

df.drop(scale_cols, axis=1, inplace=True)

df_scaled = pd.concat([df, df_scaled], axis=1)
df_scaled.head()

,Type,Machine failure,type_of_failure,Rotational speed [rpm],Torque [Nm],Tool wear [min],Air temperature [c],Process temperature [c]
0,1.0,0,5,0.222934,0.535714,0.000000,0.304348,0.358025
1,0.0,0,5,0.139697,0.583791,0.011858,0.315217,0.370370
2,0.0,0,5,0.192084,0.626374,0.019763,0.304348,0.345679
3,0.0,0,5,0.154249,0.490385,0.027668,0.315217,0.358025
4,0.0,0,5,0.139697,0.497253,0.035573,0.315217,0.370370

In [28]:
df_scaled.iloc[69]

Type                       0.000000
Machine failure            1.000000
type_of_failure            2.000000
Rotational speed [rpm]     0.140861
Torque [Nm]                0.850275
Tool wear [min]            0.754941
Air temperature [c]        0.391304
Process temperature [c]    0.407407
Name: 69, dtype: float64

## Oversampling

In [29]:
!pip uninstall scikit-learn --yes
!pip uninstall imblearn --yes

Found existing installation: scikit-learn 1.5.2
Uninstalling scikit-learn-1.5.2:
  Successfully uninstalled scikit-learn-1.5.2

WARNING: Failed to remove contents in a temporary directory 'C:\Users\gadha\anaconda3\envs\venv2\Lib\site-packages\~klearn'.
You can safely remove it manually.
WARNING: Skipping imblearn as it is not installed.

In [30]:
!pip install scikit-learn==1.2.2
!pip install imblearn

Collecting scikit-learn==1.2.2
  Downloading scikit-learn-1.2.2.tar.gz (7.3 MB)
     ---------------------------------------- 0.0/7.3 MB ? eta -:--:--
     ---- ----------------------------------- 0.8/7.3 MB 3.0 MB/s eta 0:00:03
     -------- ------------------------------- 1.6/7.3 MB 3.8 MB/s eta 0:00:02
     ------------ --------------------------- 2.4/7.3 MB 3.8 MB/s eta 0:00:02
     ----------------- ---------------------- 3.1/7.3 MB 3.8 MB/s eta 0:00:02
     --------------------- ------------------ 3.9/7.3 MB 3.7 MB/s eta 0:00:01
     ------------------------- -------------- 4.7/7.3 MB 3.7 MB/s eta 0:00:01
     ------------------------------ --------- 5.5/7.3 MB 3.7 MB/s eta 0:00:01
     --------------------------------- ------ 6.0/7.3 MB 3.7 MB/s eta 0:00:01
     ------------------------------------- -- 6.8/7.3 MB 3.7 MB/s eta 0:00:01
     ---------------------------------------- 7.3/7.3 MB 3.7 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'

  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Partial import of sklearn during the build process.
      Traceback (most recent call last):
        File "C:\Users\gadha\anaconda3\envs\venv2\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\gadha\anaconda3\envs\venv2\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\gadha\anaconda3\envs\venv2\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\gadha\AppData\Local\Temp\pip-build-env-b9j_i9rk\overlay\Lib\site-packages\setuptools\build_meta.py", line 373, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\gadha\AppData\Local\Temp\pip-build-env-b9j_i9rk\overlay\Lib\site-packages\setuptools\build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\gadha\AppData\Local\Temp\pip-build-env-b9j_i9rk\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 669, in <module>
        File "<string>", line 663, in setup_package
        File "<string>", line 597, in configure_extension_modules
        File "C:\Users\gadha\AppData\Local\Temp\pip-install-fn6b2yu9\scikit-learn_6f0de4c6e2684ea49c2c71cabf9ad2b0\sklearn\_build_utils\__init__.py", line 47, in cythonize_extensions
          basic_check_build()
        File "C:\Users\gadha\AppData\Local\Temp\pip-install-fn6b2yu9\scikit-learn_6f0de4c6e2684ea49c2c71cabf9ad2b0\sklearn\_build_utils\pre_build_helpers.py", line 82, in basic_check_build
          compile_test_program(code)
        File "C:\Users\gadha\AppData\Local\Temp\pip-install-fn6b2yu9\scikit-learn_6f0de4c6e2684ea49c2c71cabf9ad2b0\sklearn\_build_utils\pre_build_helpers.py", line 38, in compile_test_program
          ccompiler.compile(
        File "C:\Users\gadha\AppData\Local\Temp\pip-build-env-b9j_i9rk\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 379, in compile
          self.initialize()
        File "C:\Users\gadha\AppData\Local\Temp\pip-build-env-b9j_i9rk\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 289, in initialize
          vc_env = _get_vc_env(plat_spec)
                   ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\gadha\AppData\Local\Temp\pip-build-env-b9j_i9rk\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 150, in _get_vc_env
          raise DistutilsPlatformError(
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Collecting imblearn
  Downloading imblearn-0.0-py2.py3-none-any.whl.metadata (355 bytes)
Collecting imbalanced-learn (from imblearn)
  Downloading imbalanced_learn-0.12.3-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: numpy>=1.17.3 in c:\users\gadha\anaconda3\envs\venv2\lib\site-packages (from imbalanced-learn->imblearn) (2.1.1)
Requirement already satisfied: scipy>=1.5.0 in c:\users\gadha\anaconda3\envs\venv2\lib\site-packages (from imbalanced-learn->imblearn) (1.14.1)
Collecting scikit-learn>=1.0.2 (from imbalanced-learn->imblearn)
  Using cached scikit_learn-1.5.2-cp312-cp312-win_amd64.whl.metadata (13 kB)
Requirement already satisfied: joblib>=1.1.1 in c:\users\gadha\anaconda3\envs\venv2\lib\site-packages (from imbalanced-learn->imblearn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\gadha\anaconda3\envs\venv2\lib\site-packages (from imbalanced-learn->imblearn) (3.5.0)
Downloading imblearn-0.0-py2.py3-none-any.whl (1.9 kB)
Downloading imbalanced_learn-0.12.3-py3-none-any.whl (258 kB)
Using cached scikit_learn-1.5.2-cp312-cp312-win_amd64.whl (11.0 MB)
Installing collected packages: scikit-learn, imbalanced-learn, imblearn
Successfully installed imbalanced-learn-0.12.3 imblearn-0.0 scikit-learn-1.5.2

In [31]:
pip install imbalanced-learn

Requirement already satisfied: imbalanced-learn in c:\users\gadha\anaconda3\envs\venv2\lib\site-packages (0.12.3)
Requirement already satisfied: numpy>=1.17.3 in c:\users\gadha\anaconda3\envs\venv2\lib\site-packages (from imbalanced-learn) (2.1.1)
Requirement already satisfied: scipy>=1.5.0 in c:\users\gadha\anaconda3\envs\venv2\lib\site-packages (from imbalanced-learn) (1.14.1)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\users\gadha\anaconda3\envs\venv2\lib\site-packages (from imbalanced-learn) (1.5.2)
Requirement already satisfied: joblib>=1.1.1 in c:\users\gadha\anaconda3\envs\venv2\lib\site-packages (from imbalanced-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\gadha\anaconda3\envs\venv2\lib\site-packages (from imbalanced-learn) (3.5.0)
Note: you may need to restart the kernel to use updated packages.

In [32]:
from imblearn.over_sampling import SMOTE

In [33]:

smote = SMOTE(sampling_strategy='auto')

X = df_scaled.drop('type_of_failure', axis=1)
y = df_scaled['type_of_failure']

X_resampled, y_resampled = smote.fit_resample(X, y)

df_sampled = pd.concat([X_resampled, y_resampled], axis=1)
df_sampled.head()

,Type,Machine failure,Rotational speed [rpm],Torque [Nm],Tool wear [min],Air temperature [c],Process temperature [c],type_of_failure
0,1.0,0,0.222934,0.535714,0.000000,0.304348,0.358025,5
1,0.0,0,0.139697,0.583791,0.011858,0.315217,0.370370,5
2,0.0,0,0.192084,0.626374,0.019763,0.304348,0.345679,5
3,0.0,0,0.154249,0.490385,0.027668,0.315217,0.358025,5
4,0.0,0,0.139697,0.497253,0.035573,0.315217,0.370370,5

In [34]:
df_sampled.value_counts('type_of_failure')

type_of_failure
0    9652
1    9652
2    9652
3    9652
4    9652
5    9652
Name: count, dtype: int64

In [35]:
df_sampled.to_csv('../data/data_processed.csv', index=False)